import os

STREAM_DELAY = float(os.environ.get("SCREENCRASH_HOSTED_MEDIA_STREAM_DELAY", "2"))
SYNC_EVENT_INTERVAL = float(
    os.environ.get("SCREENCRASH_HOSTED_MEDIA_SYNC_EVENT_INTERVAL", "30")
)
TIME_BEFORE_FIRST_SYNC = float(
    os.environ.get("SCREENCRASH_HOSTED_MEDIA_TIME_BEFORE_FIRST_SYNC", "1")
)
SYNC_CLIENTS = os.environ.get("SCREENCRASH_HOSTED_MEDIA_SYNC_CLIENTS", "0") == "1"
